config/routes.rb
Ittest::Application.routes.draw do
  resources :questionwise_marks_distributions

  resources :options
  resources :questions
  resources :test_details
  resources :test_results
  resources :chapters
  resources :progress_report_users
  devise_for :users

  devise_scope :user do
    match '/users/sign_out', to: 'Devise::sessions#destroy', as: 'signout'
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/create_guest' => "welcome#create_guest", :as => :create_guest
  get '/contact_us' => "welcome#contact_us", :as => :contact_us
  get '/pricing' => "welcome#pricing", :as => :pricing

  get '/import_questions' => "welcome#import_questions", :as => :import_questions
  post '/importing_questions' => "questions#import", :as => :importing_questions

  get '/import_chapters' => "welcome#import_chapters", :as => :import_chapters
  post '/importing_chapters' => "chapters#import", :as => :importing_chapters

  get '/import_users' => "welcome#import_users", :as => :import_users
  post '/importing_users' => "welcome#importing_users", :as => :importing_users

  match '/test' => 'welcome#test', as: :test
  match '/test_submit' => 'test_details#test_submit', as: :test_submit
  match '/submit' => 'test_details#submit', as: :test_submit
  match '/show_results/:test_id' => 'test_details#show_details', as: :show_test_result

  root :to => 'welcome#index'

end

app/models/test_result.rb
class TestResult < ActiveRecord::Base
  attr_accessible :obj_score, :user_id, :test_time

  belongs_to :user
  has_many :test_details, dependent: :destroy
  has_one :progress_report_user, dependent: :destroy
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  # GET /test_results
  # GET /test_results.json
  def index
    @test_results = TestResult.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_results }
    end
  end

  # GET /test_results/1
  # GET /test_results/1.json
  def show
    @test_result = TestResult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_result }
    end
  end

  # GET /test_results/new
  # GET /test_results/new.json
  def new
    @test_result = TestResult.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_result }
    end
  end

  # GET /test_results/1/edit
  def edit
    @test_result = TestResult.find(params[:id])
  end

  # POST /test_results
  # POST /test_results.json
  def create
    @test_result = TestResult.new(params[:test_result])

    respond_to do |format|
      if @test_result.save
        format.html { redirect_to @test_result, notice: 'Test result was successfully created.' }
        format.json { render json: @test_result, status: :created, location: @test_result }
      else
        format.html { render action: "new" }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_results/1
  # PUT /test_results/1.json
  def update
    @test_result = TestResult.find(params[:id])

    respond_to do |format|
      if @test_result.update_attributes(params[:test_result])
        format.html { redirect_to @test_result, notice: 'Test result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_results/1
  # DELETE /test_results/1.json
  def destroy
    @test_result = TestResult.find(params[:id])
    @test_result.destroy

    respond_to do |format|
      format.html { redirect_to test_results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/test_results_helper.rb
module TestResultsHelper
end

app/views/test_results/_form.html.erb
<%= form_for(@test_result) do |f| %>
  <% if @test_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_result.errors.count, "error") %> prohibited this test_result from being saved:</h2>

      <ul>
      <% @test_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :test_count %><br />
    <%= f.number_field :test_count %>
  </div>
  <div class="field">
    <%= f.label :obj_score %><br />
    <%= f.number_field :obj_score %>
  </div>
  <div class="field">
    <%= f.label :sub_score %><br />
    <%= f.number_field :sub_score %>
  </div>
  <div class="field">
    <%= f.label :total_score %><br />
    <%= f.number_field :total_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_results/edit.html.erb
<h1>Editing test_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_result %> |
<%= link_to 'Back', test_results_path %>

app/views/test_results/index.html.erb
<style>
    #test_report_container {
        position: absolute;
        top: 10%;
        width: 97%;
        padding: 1%;
        font-family: 'Open Sans';
    }

    #test_report {
        width: 98%;
        color: #707070;
    }

    table, tr, td, th {
        border: 1px solid #ddd;
        border-collapse: collapse;
    }

    th {
        font-size: 1.2em;
        font-weight: 900;
    }

    td{
        font-size: 1.2em;
        line-height: 20px;
    }

    a {
        color: #0088CC;
        font-weight: 400;
        font-size: 14px;
    }
</style>


<div id='top_bar'>
  <a href="/" id='logo'>

  </a>
  <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <a id="contact_us_btn" class="light_button" href='/contact_us'>Contact Us</a>
  <a id="pricing_btn" class="light_button" href='/pricing'>Pricing</a>
</div>

<div id="test_report_container">
  <% if !current_user.has_paid %>
      <div class="alert_upgrade" style="width: 97.5%;">
        Upgrade for MORE Tests!!! Practice & Conquer IT!!
      </div>
      <br>
  <% end %>
  <p class='remarks' style="width: 96.5%;">
    * We provide you a score for objective questions.For subjective questions,we provide points to be included in an answer.<br>
    + Click on a pie chart to view question-wise performance for a test
  </p>
  <br>
  <br>
  <table id="test_report" class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Test No</th>
      <th>Test Date</th>
      <th>Time Taken</th>
      <th>Score*</th>
      <th>Overall Performance<sup>+</sup></th>
    </tr>
    </thead>
    <tbody>
    <% @test_results.each_with_index do |test_result, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= test_result.created_at.to_date %></td>
          <td>
            <% time = test_result.test_time.split(':') %>
            <%= time[0] + ' hours : ' + time[1] + ' minutes : ' + time[2] + ' sec' %>
          </td>
          <td style="font-size: 2em;"><%= test_result.obj_score %>/60</td>
          <td><a href="<%= show_test_result_path(test_result.id) %>"><canvas id="canvas_<%= index + 1 %>" height="100" width="100"></canvas><span style="font-size: 2em; color: #69D2E7; margin-top: 40px;" class="marks_scored"><%= (test_result.obj_score*100/60).to_s + '%' %> </span></a></td>
        </tr>
        <script>
            var data = [
                {
                    value: <%= test_result.obj_score %>,
                    color: "#69D2E7"

                },
                {
                    value: <%= 60 - test_result.obj_score %>,
                    color: "#F38630"
                }
            ];
            var ctx = document.getElementById("canvas_<%= index + 1 %>").getContext("2d");
            var piechart = new Chart(ctx).Pie(data);
        </script>
    <% end %>
    </tbody>
  </table>
  <div id='footer_panel'>
    <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
      <a href='#'><span class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function(){
      if($('#test_report_container').innerHeight() < 500){
        $('#footer_panel').css({'position': 'fixed','bottom': '10%'});
      }
  });
</script>

app/views/test_results/new.html.erb
<h1>New test_result</h1>

<%= render 'form' %>

<%= link_to 'Back', test_results_path %>

app/views/test_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @test_result.user_id %>
</p>

<p>
  <b>Test count:</b>
  <%= @test_result.test_count %>
</p>

<p>
  <b>Obj score:</b>
  <%= @test_result.obj_score %>
</p>

<p>
  <b>Sub score:</b>
  <%= @test_result.sub_score %>
</p>

<p>
  <b>Total score:</b>
  <%= @test_result.total_score %>
</p>


<%= link_to 'Edit', edit_test_result_path(@test_result) %> |
<%= link_to 'Back', test_results_path %>