config/routes.rb
Ittest::Application.routes.draw do
  resources :questionwise_marks_distributions

  resources :options
  resources :questions
  resources :test_details
  resources :test_results
  resources :chapters
  resources :progress_report_users
  devise_for :users

  devise_scope :user do
    match '/users/sign_out', to: 'Devise::sessions#destroy', as: 'signout'
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/create_guest' => "welcome#create_guest", :as => :create_guest
  get '/contact_us' => "welcome#contact_us", :as => :contact_us
  get '/pricing' => "welcome#pricing", :as => :pricing

  get '/import_questions' => "welcome#import_questions", :as => :import_questions
  post '/importing_questions' => "questions#import", :as => :importing_questions

  get '/import_chapters' => "welcome#import_chapters", :as => :import_chapters
  post '/importing_chapters' => "chapters#import", :as => :importing_chapters

  get '/import_users' => "welcome#import_users", :as => :import_users
  post '/importing_users' => "welcome#importing_users", :as => :importing_users

  match '/test' => 'welcome#test', as: :test
  match '/test_submit' => 'test_details#test_submit', as: :test_submit
  match '/submit' => 'test_details#submit', as: :test_submit
  match '/show_results/:test_id' => 'test_details#show_details', as: :show_test_result

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, except: [:contact_us, :pricing]

  def index
    @user = current_user
    @test_count = @user.max_tests.to_i - TestResult.find_all_by_user_id(@user.id).size
  end

  def test
    @test_count = current_user.max_tests.to_i - TestResult.find_all_by_user_id(current_user.id).size

    if @test_count < 0
      redirect_to index
    elsif current_user.has_paid
      @test_given = TestResult.find_all_by_user_id(current_user.id).size

      @previous_question_set = TestDetail.where(user_id: current_user.id).select(:question_id)

      previous_question_set = @previous_question_set.map { |i| i.question_id }.to_s.gsub('[', '').gsub(']', '').gsub('\'', '').split(',')

      #render text: previous_question_set
      #return

      if !@previous_question_set.blank?
        #@fill_in_the_blank_chapter = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions LEFT OUTER JOIN test_details on test_details.question_id != questions.id where questions.type = 'FillInTheBlank') a where row_number=1;")
        @fill_in_the_blank = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'FillInTheBlank' AND questions.id NOT IN (" + @previous_question_set.map { |i| i.question_id }.to_s.gsub('[', '').gsub(']', '') + ")) a where row_number=1;").sample(6)
        @fill_in_the_blank_next = Question.where(type: 'FillInTheBlank').where(['id NOT IN (?)', @fill_in_the_blank.map { |q| q.id }]).where(['id NOT IN (?)', previous_question_set.map{|i| i.to_i}]).order('RANDOM()').limit(4).sample(4)

        @true_false = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'TrueFalse' AND questions.id NOT IN (" + @previous_question_set.map { |i| i.question_id }.to_s.gsub('[', '').gsub(']', '') + ")) a where row_number=1;").sample(6)
        @true_false_next = Question.where(type: 'TrueFalse').where(['id NOT IN (?)', @true_false.map { |q| q.id }]).where(['id NOT IN (?)', previous_question_set.map{|i| i.to_i}]).order('RANDOM()').limit(4).sample(4)

        @mcq1 = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'Mcq1' AND questions.id NOT IN (" + @previous_question_set.map { |i| i.question_id }.to_s.gsub('[', '').gsub(']', '') + ")) a where row_number between 1 AND 2;").sample(12)
        @mcq1_next = Question.where(type: 'Mcq1').where(['id NOT IN (?)', @mcq1.map { |q| q.id }]).where(['id NOT IN (?)', previous_question_set.map{|i| i.to_i}]).order('RANDOM()').limit(8).sample(8)

        @mcq2 = Question.where(type: 'Mcq2').where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(5)

        @mcq3 = Question.where(type: 'Mcq3').where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(2)

        @rearrange = Question.where(type: 'Rearrange').where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(2)

        @short_note_1 = Question.where(type: 'ShortNote', weightage: 4).where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(2)

        @short_note_2 = Question.where(type: 'ShortNote', weightage: 2).where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(1)

        @html_code = Question.where(type: 'CodingOutput').where(['id NOT IN (?)', @previous_question_set.map { |i| i.question_id }]).order('RANDOM()').limit(2)
      else
        @fill_in_the_blank = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'FillInTheBlank') a where row_number=1;").sample(6)
        @fill_in_the_blank_next = Question.where(type: 'FillInTheBlank').where(['id NOT IN (?)', @fill_in_the_blank.map { |q| q.id }]).order('RANDOM()').limit(4).sample(4)

        @true_false = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'TrueFalse') a where row_number=1;").sample(6)
        @true_false_next = Question.where(type: 'TrueFalse').where(['id NOT IN (?)', @true_false.map { |q| q.id }]).order('RANDOM()').limit(4).sample(4)

        @mcq1 = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id order by random()) FROM questions where questions.type = 'Mcq1') a where row_number between 1 AND 2;").sample(12)
        @mcq1_next = Question.where(type: 'Mcq1').where(['id NOT IN (?)', @mcq1.map { |q| q.id }]).order('RANDOM()').limit(8).sample(8)

        @mcq2 = Question.where(type: 'Mcq2').order('RANDOM()').limit(5)

        @mcq3 = Question.where(type: 'Mcq3').order('RANDOM()').limit(2)

        @rearrange = Question.where(type: 'Rearrange').order('RANDOM()').limit(2)

        @short_note_1 = Question.where(type: 'ShortNote', weightage: 4).order('RANDOM()').limit(2)

        @short_note_2 = Question.where(type: 'ShortNote', weightage: 2).order('RANDOM()').limit(1)

        @html_code = Question.where(type: 'CodingOutput').order('RANDOM()').limit(2)
      end
    else
      @fill_in_the_blank = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id) FROM questions where questions.type = 'FillInTheBlank') a where row_number=1;").sample(6)
      @fill_in_the_blank_next = Question.where(type: 'FillInTheBlank').where(['id NOT IN (?)', @fill_in_the_blank.map { |q| q.id }]).limit(4).sample(4)

      @true_false = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id) FROM questions where questions.type = 'TrueFalse') a where row_number=1;").sample(6)
      @true_false_next = Question.where(type: 'TrueFalse').where(['id NOT IN (?)', @true_false.map { |q| q.id }]).limit(4).sample(4)

      @mcq1 = Question.find_by_sql("select * from (SELECT *, row_number() over (partition by chapter_id) FROM questions where questions.type = 'Mcq1') a where row_number between 1 AND 2;").sample(12)
      @mcq1_next = Question.where(type: 'Mcq1').where(['id NOT IN (?)', @mcq1.map { |q| q.id }]).limit(8).sample(8)

      @mcq2 = Question.where(type: 'Mcq2').limit(5)

      @mcq3 = Question.where(type: 'Mcq3').limit(2)

      @rearrange = Question.where(type: 'Rearrange').limit(2)

      @short_note_1 = Question.where(type: 'ShortNote', weightage: 4).limit(2)

      @short_note_2 = Question.where(type: 'ShortNote', weightage: 2).limit(1)

      @html_code = Question.where(type: 'CodingOutput').limit(2)
    end

  end

  def import_questions
    render layout: false
  end

  def import_chapters
    render layout: false
  end

  def import_users
    render layout: false
  end

  def importing_users
    if request.post? && params[:file].present?
      User.import(params[:file])
      redirect_to '/admin/user', notice: "Users imported."
    else
      redirect_to '/admin/user', notice: "Users couldn't be imported."
    end
  end

  def create_guest
    email = "#{Time.now.to_i}#{rand(99)}@guestuser.com"
    password = 'ittest_password'
    @user = User.create(email: email, password: password, password_confirmation: password, name: 'Guest', is_guest: true)
    @user.save
    sign_in(:user, @user)
    redirect_to '/admin'
  end

  def contact_us
  end

  def pricing
  end

end

app/views/welcome/contact_us.html.erb
<style>
    .contact_us_lbl {
        color: #438EB9;
        font-size: 2.5em;
    }

    #container {
        top: 20%;
        padding: 10px;
        width: 70%;
        margin-left: 10%;
    }

    #left_container {
        width: 50%;
        float: left;
    }

    #right_container {
        background-image: url("/assets/wave-pattern-white.png");
        border: 1px solid #DDDDDD;
        float: right;
        padding: 0 20px;
        width: 40%;

    }

    .contact_lbl {
        color: #E8554E;
    }

    p {
        font-size: 1.1em;
        line-height: 20px;
    }

    #happy_help {
        font-size: 2em;
        color: #87B87F;
    }
    p a {
        font-weight: 300;
    }
    p a:hover{
        color: #000000;
        text-decoration: underline;
    }

</style>
<div id='top_bar'>
  <a href="/" id='logo'>
  </a>
  <% if current_user.present? %>
      <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <% else %>
      <%= link_to 'Login', '/', id: "logout_btn", class: "red_button" %>
  <% end %>
  <a id="pricing_btn" class="light_button" href='/pricing'>Pricing</a>
</div>
<div id="container">
  <div id="left_container">
    <h1 class="contact_us_lbl">Contact Us</h1>

    <p class="text">We are here to answer any questions you may have. Reach out to us and we'll respond as soon as we
      can.</p>

    <p class="text">Even if there is something you have always wanted to get and can't find it on Let.Me.Practice., let
      us know and we promise we'll do our best to find a solution for your queries.</p>

    <h3>For Password Issue:</h3>

    <p class="text">Shoot us a mail and we will send you a new password within 1 hour to your registered email.</p>
  </div>
  <div id="right_container">
    <h1 id="happy_help">We are here to help you !!!</h1>

    <p class="contact_lbl">CALL</p>

    <p>+91-9833664934</p>

    <p class="contact_lbl">EMAIL</p>

    <p><a href="mailto:mail@letmepractice.com">mail@letmepractice.com</a></p>

    <p class="bluetext">
      If you have any queries regarding questions and their answers, kindly drop us an email and we promise to look in
      to the matter at the earliest.
    </p>
  </div>

</div>
<div id='footer_panel' style="position: absolute; top: 600px">
  <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
    <a href='#'><span class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a>
  </div>
</div>

app/views/welcome/import_chapters.html.erb
<h2>Import Chapters</h2>
<%= form_tag importing_chapters_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

app/views/welcome/import_questions.html.erb
<h2>Import Questions</h2>
<%= form_tag importing_questions_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

app/views/welcome/import_users.html.erb
<h2>Import Users</h2>
<%= form_tag importing_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

app/views/welcome/index.html.erb
<style>
    #legends {
        float: right;
        padding: 4% 2%;
        width: 40%;
    }

    .legend_label {
        font-size: 1.1em;
        font-family: 'Open Sans';
    }

    .colorize {
        padding: 0 6%;
        background-color: #000000;
    }
</style>
<div id='top_bar'>
  <a href="/" id='logo'>

  </a>
  <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <a id="contact_us_btn" class="light_button" href='/contact_us'>Contact Us</a>
  <a id="pricing_btn" class="light_button" href='/pricing'>Pricing</a>
</div>
<div id="container">
  <div id='name_text'>
    <h2>Hi, <%= @user.name %> ...</h2>

    <h2>You have <span id='test_left'><%= @test_count %></span> test(s) left.</h2>
    <br>
    <br>
    <%= link_to 'View Reports', test_results_path, id: "view_report", class: "green_button" %>
    <br>
    <br>
    <br>
    <%= link_to 'Progress Reports', progress_report_users_path, id: "progress_report", class: "blue_button" %>
    <br>
    <br>
    <br>
    <% if @test_count > 0 %>
        <%= link_to 'Take Test', test_path, id: "take_test", class: "red_button" %>
    <% end %>
  </div>
  <div id='pie_chart'>
    <h2 style="text-align: center;">Question Paper Distribution</h2>
    <canvas height="325" width="325" id="question_dist"></canvas>
    <div id="legends">
      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; Fill in the blanks (10marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; True False (10marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; MCQ1 (20marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; MCQ2 (10marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; MCQ3 (6marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; Rearrange (4marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; Short Notes (10marks)</p>

      <p class="legend_label"><span class='colorize'></span>&nbsp;&nbsp;&nbsp; Writing Program (10marks)</p>

    </div>
  </div>

  <% if !current_user.has_paid %>
      <div class="alert_upgrade" style="float: left;margin-top: 3%;">
        Upgrade for MORE Tests!!! Practice & Conquer IT!!
      </div>
  <% end %>
  <div id='footer_panel' style="position: fixed; bottom: 10%;">
    <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
      <a href='#'><span class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a>
    </div>
  </div>
</div>

<script>
    var data = [
        {
            value: 10,
            color: "#68bc31"

        },
        {
            value: 10,
            color: "#2091cf"

        },
        {
            value: 20,
            color: "#af4e96"

        },
        {
            value: 10,
            color: "#da5430"

        },
        {
            value: 6,
            color: "#001a6b"

        },
        {
            value: 4,
            color: "#848484"

        },
        {
            value: 10,
            color: "#e59729"

        },
        {
            value: 10,
            color: "#b3c1cb"

        }
    ];
    var ctx = document.getElementById("question_dist").getContext("2d");
    var piechart = new Chart(ctx).Pie(data);
    $(function () {
        $.each($('.colorize'), function (i, cell) {
            $(cell).css('background-color', data[i]['color']);
        });
    });
</script>

app/views/welcome/pricing.html.erb
<style>

    #container {
        top: 15%;
        padding: 10px;
        width: 96%;
        position: absolute;
    }

    #left_container {
        width: 50%;
        float: left;
    }

    #right_container {
        float: right;
        width: 40%;
    }

    #contact_container {
        background-image: url("/assets/wave-pattern-white.png");
        border: 1px solid #DDDDDD;
        padding: 0 20px;
        margin-top: 9%;
        height: 211px;
    }

    .contact_lbl {
        color: #E8554E;
    }

    p {
        font-size: 1.1em;
        line-height: 20px;
    }

    #happy_help {
        font-size: 2em;
        color: #87B87F;
    }

    #sign_up_btn {
        font-size: 2.2em;
        margin-top: 8.9%;
        padding: 30px 13px;
    }

    p a {
        font-weight: 300;
    }
    p a:hover{
        color: #000000;
        text-decoration: underline;
    }

</style>
<div id='top_bar'>
  <a href="/" id='logo'>
  </a>
  <% if current_user.present? %>
      <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <% else %>
      <%= link_to 'Login', '/', id: "logout_btn", class: "red_button" %>
  <% end %>
  <a id="contact_us_btn" class="light_button" href='/contact_us'>Contact Us</a>
</div>
<div id="container">
  <div id="left_container">
    <img src="assets/pricing.jpg">

    <p class="text">* First Year Launch discount of Rs. 50 on 10 Tests and Rs. 100 on 15 Tests.</p>
  </div>
  <div id="right_container">
    <div id="contact_container">
      <h1 id="happy_help">For more details:</h1>

      <p class="contact_lbl">CALL</p>

      <p>+91-9833664934</p>

      <p class="contact_lbl">EMAIL</p>

      <p><a href="mailto:mail@letmepractice.com">mail@letmepractice.com</a></p>

    </div>
    <% if current_user.present? %>
        <% if !current_user.has_paid %>
            <div class="alert_upgrade" style="float: left; margin-top: 9%; padding: 35px 5px 22px; width: 98%;">
              Upgrade for MORE Tests!!! Practice & Conquer IT!!
            </div>
        <% end %>
    <% else %>
        <%= link_to "Practice one FREE Test!!!", '/users/sign_up', id: "sign_up_btn", class: "red_button" %>
    <% end %>
  </div>

</div>
<div id='footer_panel' style="position: absolute; top: 600px">
  <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
    <a href='#'><span class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a>
  </div>
</div>