config/routes.rb
Ittest::Application.routes.draw do
  resources :questionwise_marks_distributions

  resources :options
  resources :questions
  resources :test_details
  resources :test_results
  resources :chapters
  resources :progress_report_users
  devise_for :users

  devise_scope :user do
    match '/users/sign_out', to: 'Devise::sessions#destroy', as: 'signout'
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/create_guest' => "welcome#create_guest", :as => :create_guest
  get '/contact_us' => "welcome#contact_us", :as => :contact_us
  get '/pricing' => "welcome#pricing", :as => :pricing

  get '/import_questions' => "welcome#import_questions", :as => :import_questions
  post '/importing_questions' => "questions#import", :as => :importing_questions

  get '/import_chapters' => "welcome#import_chapters", :as => :import_chapters
  post '/importing_chapters' => "chapters#import", :as => :importing_chapters

  get '/import_users' => "welcome#import_users", :as => :import_users
  post '/importing_users' => "welcome#importing_users", :as => :importing_users

  match '/test' => 'welcome#test', as: :test
  match '/test_submit' => 'test_details#test_submit', as: :test_submit
  match '/submit' => 'test_details#submit', as: :test_submit
  match '/show_results/:test_id' => 'test_details#show_details', as: :show_test_result

  root :to => 'welcome#index'

end

app/models/test_detail.rb
class TestDetail < ActiveRecord::Base
  attr_accessible :answer, :question_id, :score, :test_result_id, :user_id, :question_type

  belongs_to :user
  belongs_to :test_result
  belongs_to :question
end

app/controllers/test_details_controller.rb
class TestDetailsController < ApplicationController
  # GET /test_details
  # GET /test_details.json
  def index
    @test_details = TestDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_details }
    end
  end

  # GET /test_details/1
  # GET /test_details/1.json
  def show
    @test_detail = TestDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_detail }
    end
  end

  # GET /test_details/new
  # GET /test_details/new.json
  def new
    @test_detail = TestDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_detail }
    end
  end

  # GET /test_details/1/edit
  def edit
    @test_detail = TestDetail.find(params[:id])
  end

  # POST /test_details
  # POST /test_details.json
  def create
    render json: params
    return

    @test_detail = TestDetail.new(params[:test_detail])

    respond_to do |format|
      if @test_detail.save
        format.html { redirect_to @test_detail, notice: 'Test detail was successfully created.' }
        format.json { render json: @test_detail, status: :created, location: @test_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @test_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_details/1
  # PUT /test_details/1.json
  def update
    @test_detail = TestDetail.find(params[:id])

    respond_to do |format|
      if @test_detail.update_attributes(params[:test_detail])
        format.html { redirect_to @test_detail, notice: 'Test detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_details/1
  # DELETE /test_details/1.json
  def destroy
    @test_detail = TestDetail.find(params[:id])
    @test_detail.destroy

    respond_to do |format|
      format.html { redirect_to test_details_url }
      format.json { head :no_content }
    end
  end

  # Used for checking the test being submitted by user.
  def test_submit
    received_params = params
    received_params.delete(:authenticity_token)
    received_params.delete(:controller)
    received_params.delete(:action)

    time = received_params['time_taken'].split(':')
    time_taken = '' + (2 - time[0].to_i).to_s + ':' + (30 - time[1].to_i).to_s + ':' + (60 - time[2].to_i).to_s

    received_params.delete(:time_taken)

    final_score = 0

    @test = TestResult.create(user_id: current_user.id, test_time: time_taken)

    received_params.each do |param|
      @question = Question.find (param[0])
      #puts '====>> ' + (param[1].nil? || param[1] === '').to_s
      if (param[1].nil? || param[1] === '' || param[1] === 'None')
        ans='Not Attempted'
        @test.test_details.create(question_id: @question.id, answer: ans, user_id: current_user.id, question_type: @question.type, score: 0)
      else
        ans = param[1]
        final_ans = ''
        score = 0
        if (@question.type === 'FillInTheBlank' || @question.type === 'Rearrange')
          ans = ans.strip
          @option = Option.where(question_id: param[0])
          @option.each do |option|
            (option.key.casecmp(ans) == 0) ? score = @question.options.first.val : score = 0
          end
          final_score += score
          @test.test_details.create(question_id: @question.id, answer: ans, user_id: current_user.id, question_type: @question.type, score: score)
        elsif (@question.type === 'TrueFalse' || @question.type === 'Mcq1')
          score = ans.split('_')[1].to_i
          final_score += score
          puts '======>>' + @question.type
          @test.test_details.create(question_id: @question.id, answer: ans.split('_')[0], user_id: current_user.id, question_type: @question.type, score: score)
        elsif (@question.type === 'Mcq2' || @question.type === 'Mcq3')
          if param[1].size < 2
            final_ans = 'Not Attempted'
            score = 0
          else
            ans.each do |answer|
              if (answer != 'None')
                @option = Option.find(answer.to_i)
                final_ans += @option.key + '||'
                score += @option.val
              end
            end
          end
          final_score += score
          @test.test_details.create(question_id: @question.id, answer: final_ans, user_id: current_user.id, question_type: @question.type, score: score)
        else
          @test.test_details.create(question_id: @question.id, answer: ans, user_id: current_user.id, question_type: @question.type)
        end
      end
    end

    @test.update_attribute(:obj_score, final_score)

    @questionwise_score = TestDetail.group(:question_type, :test_result_id).having(test_result_id: @test.id).sum(:score)

    @questionwise_score.each do |qscore|
      case qscore[0][0]
        when 'FillInTheBlank'
          @fill_score = qscore[1].to_i
        when 'TrueFalse'
          @tf_score = qscore[1].to_i
        when 'Mcq1'
          @mcq1_score = qscore[1].to_i
        when 'Mcq2'
          @mcq2_score = qscore[1].to_i
        when 'Mcq3'
          @mcq3_score = qscore[1].to_i
        when 'Rearrange'
          @rearrange_score = qscore[1].to_i
      end
    end
    ProgressReportUser.create(user_id: current_user.id, test_result_id: @test.id, fill: 'FillInTheBlank', fill_score: @fill_score, tf: 'TrueFalse', tf_score: @tf_score, mcq1: 'Mcq1', mcq1_score: @mcq1_score, mcq2: 'Mcq2', mcq2_score: @mcq2_score, mcq3: 'Mcq3', mcq3_score: @mcq3_score, rearrange: 'Rearrange', rearrange_score: @rearrange_score)
    render action: "submit"
  end

  def submit
  end

  def show_details
    test_id = params[:test_id]
    @test_details = TestDetail.find_all_by_test_result_id(test_id)
    @question_ids = @test_details.map { |td| td.question_id }
    @fill_in_the_blank = Question.where(['id IN (?) AND type = (?)', @question_ids, 'FillInTheBlank'])
    @true_false = Question.where(['id IN (?) AND type = (?)', @question_ids, 'TrueFalse'])
    @mcq1 = Question.where(['id IN (?) AND type = (?)', @question_ids, 'Mcq1'])
    @mcq2 = Question.where(['id IN (?) AND type = (?)', @question_ids, 'Mcq2'])
    @mcq3 = Question.where(['id IN (?) AND type = (?)', @question_ids, 'Mcq3'])
    @rearrange = Question.where(['id IN (?) AND type = (?)', @question_ids, 'Rearrange'])
    @short_note_1 = Question.where(['id IN (?) AND type = (?) AND weightage = (?)', @question_ids, 'ShortNote', 4])
    @short_note_2 = Question.where(['id IN (?) AND type = (?) AND weightage = (?)', @question_ids, 'ShortNote', 2])
    @html_code = Question.where(['id IN (?) AND type = (?)', @question_ids, 'CodingOutput'])

    @questionwise_score = TestDetail.group(:question_type, :test_result_id).having(test_result_id: test_id).sum(:score)

    @questionwise_score.each do |qscore|
      case qscore[0][0]
        when 'FillInTheBlank'
          @fill_score = qscore[1].to_i
        when 'TrueFalse'
          @tf_score = qscore[1].to_i
        when 'Mcq1'
          @mcq1_score = qscore[1].to_i
        when 'Mcq2'
          @mcq2_score = qscore[1].to_i
        when 'Mcq3'
          @mcq3_score = qscore[1].to_i
        when 'Rearrange'
          @rearrange_score = qscore[1].to_i
      end
    end

  end

end

app/helpers/test_details_helper.rb
module TestDetailsHelper
end

app/views/test_details/_form.html.erb
<%= form_for(@test_detail) do |f| %>
  <% if @test_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_detail.errors.count, "error") %> prohibited this test_detail from being saved:</h2>

      <ul>
      <% @test_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_id %><br />
    <%= f.number_field :test_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_details/edit.html.erb
<h1>Editing test_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_detail %> |
<%= link_to 'Back', test_details_path %>

app/views/test_details/index.html.erb
<h1>Listing test_details</h1>

<table>
  <tr>
    <th>Test</th>
    <th>Question</th>
    <th>Answer</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_details.each do |test_detail| %>
  <tr>
    <td><%#= test_detail.test_id %></td>
    <td><%= test_detail.question_id %></td>
    <td><%= test_detail.answer %></td>
    <td><%= test_detail.score %></td>
    <td><%= link_to 'Show', test_detail %></td>
    <td><%= link_to 'Edit', edit_test_detail_path(test_detail) %></td>
    <td><%= link_to 'Destroy', test_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test detail', new_test_detail_path %>

app/views/test_details/new.html.erb
<h1>New test_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', test_details_path %>

app/views/test_details/show.html.erb
<!DOCTYPE html>
<p id="notice"><%= notice %></p>

<p>
  <b>Test:</b>
  <%= @test_detail.test_id %>
</p>

<p>
  <b>Question:</b>
  <%= @test_detail.question_id %>
</p>

<p>
  <b>Answer:</b>
  <%= @test_detail.answer %>
</p>

<p>
  <b>Score:</b>
  <%= @test_detail.score %>
</p>


<%= link_to 'Edit', edit_test_detail_path(@test_detail) %> |
<%= link_to 'Back', test_details_path %>

<html>
<head>
  <title><img src='assets/logo.png'> - A platform for FYJC students of Mumbai University to give online IT Tests</title>
  <%= csrf_meta_tag %>
  <link href="assets/main.css" rel="stylesheet">
  <link href="assets/test.css" rel="stylesheet">
  <link href="assets/home.css" rel="stylesheet">
  <script src="assets/Chart.js"></script>
</head>
<body>
<div id='instruction_panel'>
  <div id='instruction_container'>
    <h2>Instructions</h2>
    <hr>
    <div id="instruction_content">
      <ol>
        <li>You will be provided with two and half hours to complete HSC Online IT test Examination</li>
        <li>Test consists of total of 8 questions and total of 80 marks</li>
        <li>There is NO negative marking for any question</li>
        <li>In case the time period gets over,test will be automatically submitted</li>
        <li>You can view test performance for objective questions as soon as the test is submitted
          For subjective questions, result is expected to come within two days</li>
        <li>Keep Practising!!</li>
      </ol>

    </div>
    <div id="start_test_btn" class="red_button">Start Test</div>
  </div>
</div>
<div id="test_panel">
<div id='top_bar'>
  <a href="/" id='logo'>

  </a>
  <div id='counter'>

  </div>
  <div class="name_div"><h3>Hi, <%= current_user.name %> </h3></div>

</div>
<form method="post" action="/test_submit">
<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>

<div id='left_panel'>
  <a href='#' id='q1' class="question_list">Question 1</a>
  <a href='#' id='q2' class="question_list">Question 2</a>
  <a href='#' id='q3' class="question_list">Question 3</a>
  <a href='#' id='q4' class="question_list">Question 4</a>
  <a href='#' id='q5' class="question_list">Question 5</a>
  <a href='#' id='q6' class="question_list">Question 6</a>
  <a href='#' id='q7' class="question_list">Question 7</a>
  <a href='#' id='q8' class="question_list">Question 8</a>
  <input type="submit" value="Submit Test" class="submit_btn red_button">
</div>
<div id='main_content'>
<div id='q1_div' style="display: block" class='content active'>
  <h3>Question 1 >> Fill in the blank<span class="weightage">(1 X 10)</span></h3>
  <hr>
  <br>
  <div>
    <canvas style="text-align:left" id="myChart" width="200" height="200"></canvas>
    <h2 style="float: right;">You have got <span id="test_left">7</span> correct answers out of 10</h2>
    <img src="assets/correct1.jpeg" style="width:50px;height:50px;"> correct answer
    <img src="assets/wrong1.jpeg" style="width:50px;height:50px;"> wrong answer
  </div>
  <script>
      var ctx = document.getElementById("myChart").getContext("2d");

      var data = [
          /* {
           value: 4,
           //color:"#D15B47"
           //  color:"#0EAA00"
           color:"#008700"

           },*/
          {
              value: 7,
              //color:"#D15B47"
              //  color:"#0EAA00"
              color:"#069104"

          },
          /*{
           value: 12,
           //color:"#D15B47"
           //  color:"#0EAA00"
           color:"#018402"

           },*/


          /* {
           value: 4,
           //color:"#D15B47"
           color:"#008000"
           },*/
          {
              value: 2,
              //color:"#D15B47"
              color:"#FD2317"
          }
      ];
      var piechart=new Chart(ctx).Pie(data);
  </script>
  <ol id='fill'>
    <% @fill_in_the_blank.each_with_index do |fill, index| %>
        <li>
          <div class="srno_field"><%= (index+1) %></div>
          <div class="que_field"><%= fill.cipher %></div>
          <!--<input type="hidden" value="<%= fill.id %>">-->

          <div class="ans_field"><input type="text" size="15" name="<%= fill.id %>"></div>
        </li>
    <% end %>
    <% @fill_in_the_blank_next.each_with_index do |fill, index| %>
        <li>
          <div class="srno_field"><%= (index+7) %></div>
          <div class="que_field"><%= fill.cipher %></div>
          <!-- <input type="hidden" value="<%= fill.id %>">-->

          <div class="ans_field"><input type="text" size="15" name="<%= fill.id %>"></div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q2_div' class='content'>
  <h3>Question 2 >> State whether True or False<span class="weightage">(1 X 10)</span></h3>
  <hr>
  <br>
  <ol id='TF'>
    <% @true_false.each_with_index do |tf, index| %>
        <li>
          <div class="srno_field"><%= (index+1) %></div>
          <div class="que_field"><%= tf.cipher %></div>

          <div class="ans_field">
            <input type="radio" name="<%= tf.id %>" value="None" class='hide' checked="true">
            <% tf.options.each do |option| %>
                <input type="radio" name="<%= tf.id %>" value="<%= option.key %>_<%= option.val %>"><%= option.key %>
            <% end %>
            <!-- <input type="radio" name="<%= tf.id %>" value="True">True &nbsp;&nbsp;-->
            <!--<input type="radio" name="<%= tf.id %>" value="False">False-->

          </div>
        </li>
    <% end %>
    <% @true_false_next.each_with_index do |tf, index| %>
        <li>
          <div class="srno_field"><%= (index+7) %></div>
          <div class="que_field"><%= tf.cipher %></div>

          <div class="ans_field">
            <input type="radio" name="<%= tf.id %>" value="None" class='hide' checked="true">
            <% tf.options.each do |option| %>
                <input type="radio" name="<%= tf.id %>" value="<%= option.key %>_<%= option.val %>"><%= option.key %>
            <% end %>
            <!-- <input type="radio" name="<%= tf.id %>" value="True">True &nbsp;&nbsp;
            <input type="radio" name="<%= tf.id %>">False
            <input type="radio" name="<%= tf.id %>" value="None" class='hide' checked="true">-->
          </div>
        </li>
    <% end %>

  </ol>

</div>
<div id='q3_div' class='content '>
  <h3>Question 3 >> Multiple Choice with one correct<span class="weightage">(1 X 20)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @mcq1.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <ul>
              <% qn.options.each do |option| %>
                  <li>
                    <input type="radio" name="<%= qn.id %>" value="<%= option.key %>_<%= option.val %>"><%= option.key %>
                  </li>
              <% end %>
              <li>
                <input type="radio" name="<%= qn.id %>" value="None" class='hide' checked="true">
              </li>
            </ul>
          </div>
        </li>
    <% end %>
    <% @mcq1_next.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 19 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <ul>
              <% qn.options.each do |option| %>
                  <li>
                    <input type="radio" name="<%= qn.id %>" id="<%= option.id %>" value="<%= option.key %>_<%= option.val %>"><%= option.key %>
                  </li>
              <% end %>
              <li>
                <input type="radio" name="<%= qn.id %>" value="None" class='hide' checked="true">
              </li>
            </ul>
          </div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q4_div' class='content '>
  <h3>Question 4 >> Multiple Choice with two correct<span class="weightage">(2 X 5)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @mcq2.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <ul>
              <li>
                <%= check_box_tag(qn.id.to_s + '[]', 'None', checked = true, options = {class: 'hide'}) %>
              </li>
              <% qn.options.each_with_index do |option, index| %>
                  <li>
                    <%= check_box_tag(qn.id.to_s + '[]', option.id.to_s + '_' + option.val.to_s, checked = false, options = {}) %><%= option.key %>
                  </li>
              <% end %>
            </ul>
          </div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q5_div' class='content'>
  <h3>Question 5 >> Multiple Choice with three correct<span class="weightage">(2 X 3)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @mcq3.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <ul>
              <li>
                <%= check_box_tag(qn.id.to_s + '[]', 'None', checked = true, options = {class: 'hide'}) %>
              </li>
              <% qn.options.each_with_index do |option, index| %>
                  <li>
                    <%= check_box_tag(qn.id.to_s + '[]', option.id.to_s + '_' + option.val.to_s, checked = false, options = {}) %><%= option.key %>
                  </li>
              <% end %>
            </ul>
          </div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q6_div' class='content '>
  <h3>Question 6 >> Rearrange in correct sequence<span class="weightage">(2 X 2)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @rearrange.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <ul>
              <% qn.options.each do |option| %>
                  <li>
                    <input type="text" name="<%= qn.id %>" id="<%= option.id %>">
                  </li>
              <% end %>
            </ul>
          </div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q7_div' class='content '>
  <h3>Question 7(a) >> Answer in brief<span class="weightage">(4 X 2)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @short_note_1.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <textarea name="<%= qn.id %>" ></textarea>
          </div>
        </li>
    <% end %>
  </ol>
  <br>

  <h3>Question 7(b) >> Answer in brief<span class="weightage">(2 X 1)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @short_note_2.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_mcq"><%= qn.cipher %></div>
          <br>
          <br>

          <div class="ans_field_mcq">
            <textarea name="<%= qn.id %>"></textarea>
          </div>
        </li>
    <% end %>
  </ol>
</div>
<div id='q8_div' class='content '>
  <h3>Question 8 >> Write the program for given output<span class="weightage">(5 X 2)</span></h3>
  <hr>
  <br>
  <ol class="mcq">
    <% @html_code.each_with_index do |qn, index| %>
        <li>
          <div class="srno_field"><%= index + 1 %></div>
          <div class="que_field_html"><%= qn.cipher %><br><br>
            <img src="<%= qn.img.url %>">
          </div>
          <br>
          <br>

          <div class="ans_field_html ans_field_mcq">
            <textarea name="<%= qn.id %>"></textarea>
          </div>
        </li>
    <% end %>
    </li>
  </ol>
</div>
</div>
</form>
</div>
<script src="assets/test.js"></script>
</body>
</html>

app/views/test_details/submit.html.erb
<style>
    #main_content {
        top: 15%;
        padding: 10% 5%;
        width: 90%;
        font-family: 'Open Sans';
        left: 0;
    }

    #leftside {
        width: 60%;
        float: left;
        color: #7A7A7A;
        font-weight: 300;
        text-align: right;
        padding-right: 10%;
    }

    #rightside {
        width: 30%;
        float: right;
    }

    h1 {
        font-size: 4em;
        margin-top: 2.5%;
        line-height: 1em;
    }

    #continue {
        font-size: 2em;
        padding: 2% 22%;
        color: #ffffff;
    }
</style>
<div id='top_bar'>
  <a href="/" id='logo'>
  </a>
  <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <a id="contact_us_btn" class="light_button" href='/contact_us'>Contact Us</a>
  <a id="pricing_btn" class="light_button" href='/pricing'>Pricing</a>
</div>
<div id='main_content'>
  <% if !current_user.has_paid %>
      <div class="alert_upgrade" style="width: 99.3%; margin-top: -10%">
        Upgrade for MORE Tests!!! Practice & Conquer IT!!
      </div>
      <br>
  <% end %>
    <div id="leftside">
        <h1>Test is submitted successfully!!</h1><br>
        <a href="<%= test_results_path %>" id='continue' class='green_button'>View Results</a>
    </div>
    <div id="rightside">
        <img src="assets/gears.gif">
    </div>
    <div id='footer_panel'>
        <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
            <a href='#'><span
                class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a></div>
    </div>
</div>