config/routes.rb
Ittest::Application.routes.draw do
  resources :questionwise_marks_distributions

  resources :options
  resources :questions
  resources :test_details
  resources :test_results
  resources :chapters
  resources :progress_report_users
  devise_for :users

  devise_scope :user do
    match '/users/sign_out', to: 'Devise::sessions#destroy', as: 'signout'
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/create_guest' => "welcome#create_guest", :as => :create_guest
  get '/contact_us' => "welcome#contact_us", :as => :contact_us
  get '/pricing' => "welcome#pricing", :as => :pricing

  get '/import_questions' => "welcome#import_questions", :as => :import_questions
  post '/importing_questions' => "questions#import", :as => :importing_questions

  get '/import_chapters' => "welcome#import_chapters", :as => :import_chapters
  post '/importing_chapters' => "chapters#import", :as => :importing_chapters

  get '/import_users' => "welcome#import_users", :as => :import_users
  post '/importing_users' => "welcome#importing_users", :as => :importing_users

  match '/test' => 'welcome#test', as: :test
  match '/test_submit' => 'test_details#test_submit', as: :test_submit
  match '/submit' => 'test_details#submit', as: :test_submit
  match '/show_results/:test_id' => 'test_details#show_details', as: :show_test_result

  root :to => 'welcome#index'

end

app/models/progress_report_user.rb
class ProgressReportUser < ActiveRecord::Base
  attr_accessible :user_id, :test_result_id, :fill, :fill_score, :tf, :tf_score, :mcq1, :mcq1_score, :mcq2, :mcq2_score, :mcq3, :mcq3_score, :rearrange,:rearrange_score

  belongs_to :user
  belongs_to :test_result
end

app/controllers/progress_report_users_controller.rb
class ProgressReportUsersController < ApplicationController
  # GET /progress_report_users
  # GET /progress_report_users.json
  def index
    @progress_report_users = ProgressReportUser.where(user_id: current_user.id).order('test_result_id desc limit 3')
    @test_count = TestResult.find_all_by_user_id(current_user.id).size
    #@test_time = []
    #@progress_report_users.each do |rep|
    #  @test_time.push(TestResult.find(rep.test_result_id).test_time)
    #end

    #render json: @test_time
    #return
    key_array = ['fill_score', 'tf_score', 'mcq1_score', 'mcq2_score', 'mcq3_score', 'rearrange_score']
    @final_hash = []
    @progress_report_users.each do |report|
      key_array.each do |key|
        score = (report[key].nil?)? 0 : report[key]
        @final_hash.push(score)
      end
    end
  end

  # GET /progress_report_users/1
  # GET /progress_report_users/1.json
  def show
    @progress_report_user = ProgressReportUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @progress_report_user }
    end
  end

  # GET /progress_report_users/new
  # GET /progress_report_users/new.json
  def new
    @progress_report_user = ProgressReportUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @progress_report_user }
    end
  end

  # GET /progress_report_users/1/edit
  def edit
    @progress_report_user = ProgressReportUser.find(params[:id])
  end

  # POST /progress_report_users
  # POST /progress_report_users.json
  def create
    @progress_report_user = ProgressReportUser.new(params[:progress_report_user])

    respond_to do |format|
      if @progress_report_user.save
        format.html { redirect_to @progress_report_user, notice: 'Progress report user was successfully created.' }
        format.json { render json: @progress_report_user, status: :created, location: @progress_report_user }
      else
        format.html { render action: "new" }
        format.json { render json: @progress_report_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /progress_report_users/1
  # PUT /progress_report_users/1.json
  def update
    @progress_report_user = ProgressReportUser.find(params[:id])

    respond_to do |format|
      if @progress_report_user.update_attributes(params[:progress_report_user])
        format.html { redirect_to @progress_report_user, notice: 'Progress report user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @progress_report_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_report_users/1
  # DELETE /progress_report_users/1.json
  def destroy
    @progress_report_user = ProgressReportUser.find(params[:id])
    @progress_report_user.destroy

    respond_to do |format|
      format.html { redirect_to progress_report_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/progress_report_users_helper.rb
module ProgressReportUsersHelper
end

app/views/progress_report_users/_form.html.erb
<%= form_for(@progress_report_user) do |f| %>
  <% if @progress_report_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress_report_user.errors.count, "error") %> prohibited this progress_report_user from being saved:</h2>

      <ul>
      <% @progress_report_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progress_report_users/edit.html.erb
<h1>Editing progress_report_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress_report_user %> |
<%= link_to 'Back', progress_report_users_path %>

app/views/progress_report_users/index.html.erb
<style>

    #progress_report_table_container {
        font-family: 'Open Sans';
        padding: 2%;
        position: absolute;
        top: 10%;
        width: 95%;
    }

    #progress_report_table {
        width: 100%;
    }

    table, tr, td, th {
        border: 1px solid #ddd;
        border-collapse: collapse;
    }

    .pie_reports td canvas {
        margin-left: -50%;
    }

    .label {
        font-size: 1.3em;
        line-height: 20px;
        width: 20%;
        text-align: left;
    }

    .marks_scored {
        padding-left: 1%;
    }

</style>
<script type="text/javascript">
    $(function () {
        var test_format = [10, 10, 20, 10, 6, 4];
        var question_keys = ["Fill in the blanks", "True False", "MCQ1", "MCQ2", "MCQ3", "Rearrange"];
        var colors_array = ['#A0408B', '#69D2E7', '#275AA2', '#158875', '#0E6892', '#4D5360']
        var score_array = <%= @final_hash %>
        var test_count = <%= @test_count %>

        var toAppend_head = "<tr>";
        toAppend_head += "<th>Question Type</th>";
        for (var index = 0; index < <%= @final_hash.size/6 %>; index++) {
            toAppend_head += "<th>Test No " + (test_count - index) + "</th>";
        }
        toAppend_head += "</tr>";
        $('table#progress_report_table thead').append(toAppend_head);

        var toAppend;

        var que_index = 0, end = question_keys.length, loop_count = 0;
        for (var index = 1; index <= <%= @progress_report_users.size %>; index++) {
            var row_count = 0;
            for (var que_index = que_index; que_index < end; que_index++) {
                if (loop_count == 0) {
                    toAppend = '<tr id="row_' + row_count + '">';
                    toAppend += "<td class='label'>" + question_keys[que_index] + "</td></tr>";
                    $('table#progress_report_table tbody').append(toAppend);
                }
                var pieData = [
                    {
                        value: (test_format[row_count] - score_array[que_index]),
                        color: "#F38630"
                    },
                    {
                        value: score_array[que_index],
                        color: colors_array[row_count]
                    }
                ];
                canvas_name = "canvas_" + question_keys[row_count] + "_" + index;
                toAppend = "<td><canvas id=\"" + canvas_name + "\" height=\"75\" width=\"75\"></canvas><span class='marks_scored'>You scored: " + score_array[que_index] + "/" + test_format[row_count] + "</span></td>";
                $('#row_' + row_count).append(toAppend);
                var myPie = new Chart(document.getElementById(canvas_name).getContext("2d")).Pie(pieData);
                toAppend = "</tr>";
                $('table#progress_report_table tbody').append(toAppend);
                row_count += 1;
            }
            if (end < <%= @final_hash.size %>) {
                end += 6;
            }
            loop_count += 1;
        }
    });
</script>
<div id='top_bar'>
  <a href="/" id='logo'>

  </a>
  <%= link_to 'Logout', signout_path, id: "logout_btn", class: "red_button" %>
  <a id="contact_us_btn" class="light_button" href='/contact_us'>Contact Us</a>
  <a id="pricing_btn" class="light_button" href='/pricing'>Pricing</a>
</div>
<div id="progress_report_table_container">
  <% if !current_user.has_paid %>
      <div class="alert_upgrade" style="width: 99.3%;">
        Upgrade for MORE Tests!!! Practice & Conquer IT!!
      </div>
      <br>
  <% end %>
  <p class="remarks" style="width: 98.5%;">The progress report below shows your performance in last 3 tests.</p>
  <table id='progress_report_table' class="table table-striped table-bordered">
    <thead>
    </thead>
    <tbody class="pie_reports">
    </tbody>
  </table>
  <div id='footer_panel' style="width: 100%;">
    <div id='copyright'>All Rights Reserved. 2013 <span class="copy_sym">&copy;</span>
      <a href='#'><span class="Y YB_logo">Yuva</span><span class="B YB_logo">Beat</span></a>
    </div>
  </div>
</div>

app/views/progress_report_users/new.html.erb
<h1>New progress_report_user</h1>

<%= render 'form' %>

<%= link_to 'Back', progress_report_users_path %>

app/views/progress_report_users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_progress_report_user_path(@progress_report_user) %> |
<%= link_to 'Back', progress_report_users_path %>